[phases.setup]
nixPkgs = ["ffmpeg", "curl"]

[phases.build]
commands = [
  "mkdir -p /usr/local/bin",
  "curl -L https://github.com/DanielSWolf/rhubarb-lip-sync/releases/download/v1.10.0/rhubarb-1.10.0-linux.zip -o rhubarb.zip",
  "unzip rhubarb.zip -d /usr/local/bin",
  "chmod +x /usr/local/bin/rhubarb"
]

[phases.start]
runtime = "nodejs-18"
